### ISSUE TITLE
Rebase tracking meta-issue.

### ISSUE THREAD

**Issue by emilio** [servo/gecko-dev#2]
This is just an issue to track down when we rebase over m-c.

**Comment by emilio** [comment]
Just rebased to current tip: https://github.com/mozilla/gecko-dev/commit/92616e983b8ad6e99ec148f341e146c3c6fa312a

**Comment by Manishearth** [comment]
Did you do a bindings resync on the servo side? I was having issues.

**Comment by emilio** [comment]
That's https://github.com/servo/servo/pull/12339. Landed in Gecko before Servo, just sayin' :P

**Comment by Manishearth** [comment]
😄

**Comment by Manishearth** [comment]
Wait, so this repo needs that patch to be applied to work properly? The point of the workflow is that ideally you should never/rarely have to apply a patch manually, you can just pull in servo master and the stylo branch here -- so things should get cherry-picked/rebased only after the corresponding PRs land in servo.

(We can do it the other way too, but "landed in m-c tip" is a less concrete concept because of backouts and the delay in syncing with gecko-dev)

**Comment by emilio** [comment]
There hasn't been any patch applied manually, the relevant Gecko changes are on m-c. Should we just don't rebase until a point when everything is stable from servo's point of view?

**Comment by emilio** [comment]
(That sounds reasonable, though things could get stuck easily)

**Comment by emilio** [comment]
Also, you shouldn't have problems with the bindings AFAIK, the gecko patches added only Gecko-side functions, so there shouldn't be any problem.

**Comment by Manishearth** [comment]
> There hasn't been any patch applied manually,

I mean, the servo-side stuff needs to be applied manually for this to work.

> Should we just don't rebase until a point when everything is stable from servo's point of view?

Yep.

**Comment by Manishearth** [comment]
> Also, you shouldn't have problems with the bindings AFAIK

Ah, right. This does muck up the bindings generation but that's okay.

**Comment by Manishearth** [comment]
Added https://bugzilla.mozilla.org/show_bug.cgi?id=1285235, which has been checked in to m-i

**Comment by emilio** [comment]
Just rebased to this morning's m-c

**Comment by Manishearth** [comment]
Please re-sync the bindings when you do this 😄 

https://gist.github.com/Manishearth/922222375ca020af322fe975cca3f52d

(I'm on it)

**Comment by emilio** [comment]
Whoops, good catch, I thought no bindings will need to be updated, but
forgot the quick style="" fix of heycam had already landed.

**Comment by Manishearth** [comment]
Also updating bindgen causes some changes.

https://github.com/servo/servo/pull/12499 is the sync, though I'm going to include that commit in my calc PR anyway so it doesn't need to merge

**Comment by Manishearth** [comment]
I tried rebasing, but there are a couple of issues. My bindgen is mysteriously broken (it was working yesterday), with the following link error:

```
error: linking with `cc` failed: exit code: 1
note: "cc" "-m64" "-L" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/bindgen.0.o" "-o" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/bindgen" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug" "-L" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps" "-L" "/usr/local/opt/llvm38/lib/llvm-3.8/lib" "-L" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/libbindgen.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libclang_sys-6899b0c0746b25a3.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libglob-028bcc81f721b7f5.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libaster-442b4d783d9e4aa4.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libbitflags-0e272044714c8076.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libquasi-04e77aa9194a1003.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libsyntex_syntax-aed1acccb8e1590a.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libsyntex_errors-ca9bf8148343fe4e.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libunicode_xid-6613e5c0eda58b13.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/liblibc-1f3392fe1afd1313.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libterm-44dfa57762d62876.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libbitflags-1efefdc447eb53f2.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/liblog-bf16bb9a4912b11d.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/libsyntex_pos-d76d45a2431741ad.rlib" "/Users/manishearth/mozilla/geckolib/ports/geckolib/gecko_bindings/tools/rust-bindgen/target/debug/deps/librustc_serialize-3561541d79c18212.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-c8005792.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-c8005792.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-c8005792.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librand-c8005792.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcollections-c8005792.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_unicode-c8005792.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-c8005792.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc_jemalloc-c8005792.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-c8005792.rlib" "/Users/manishearth/.multirust/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-c8005792.rlib" "-l" "clang" "-l" "System" "-l" "pthread" "-l" "c" "-l" "m" "-l" "compiler-rt"
note: Undefined symbols for architecture x86_64:
  "_clang_Type_getNamedType", referenced from:
      bindgen::clang::Type::named::h017a16ee858af8af in libbindgen.rlib(bindgen.0.o)
  "_clang_Cursor_isFunctionInlined", referenced from:
      bindgen::clang::Cursor::is_inlined_function::hbf3ecb6d1f288ea8 in libbindgen.rlib(bindgen.0.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: aborting due to previous error
error: Could not compile `bindgen`.

To learn more, run the command again with --verbose.

bindings::None failed
```

Additionally, the rebase doesn't compile with 

```
10:29.75 In file included from /Users/manishearth/mozilla/quantum-central/obj-x86_64-apple-darwin15.3.0/dom/base/Unified_cpp_dom_base4.cpp:128:
10:29.75 /Users/manishearth/mozilla/quantum-central/dom/base/nsDocument.cpp:13546:71: error: use of undeclared identifier 'NS_STYLE_HINT_NONE'
10:29.75   restyleManager->AsGecko()->PostRestyleEvent(root, eRestyle_Subtree, NS_STYLE_HINT_NONE);
```

**Comment by Manishearth** [comment]
Rebased. 

Was at 3b04a1e5405c4ee6ce189b72ef17dac4de7520a0.

Now at 0ca7aac96cb4e87a6676ba74a13e10543323aa74

Corresponding Servo sync: https://github.com/servo/servo/pull/12517

**Comment by Manishearth** [comment]
The next rebase makes bindgen error because of 381cbd207beb6c196f368b44ccfbab9b275cdb21 -- it can no longer generate both structs_debug and structs_release from one build dir.

I'm not even sure if it makes sense to generate structs_release from a debug build dir, though it seems to work okay. Perhaps we can just bypass this check for stylo?

**Comment by Manishearth** [comment]
With that commit reverted, I get a "no input files given" error for structs, though bindings works fine. I'll look at it tomorrow. In the meantime, the stylo-rebase branch contains the rebase.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/12599 will merge soon, we should update stylo with stylo-rebase when it does.

**Comment by bholley** [comment]
I updated with stylo-rebase, but compilation was busted due to a mismerge on that stylo UI patch. I've just stripped that one out and a few others so that we can reduce the number of hacks we have in the tree.

**Comment by Manishearth** [comment]
Shoot. I had fixed that, but forgot to push.

**Comment by bholley** [comment]
I pushed a rebase slightly too soon, and Emilio's pr bounced on an intermittent again. Hopefully the problem should be resolved within the hour.

**Comment by Manishearth** [comment]
Latest rebase in 848b0d0db9fe5b668b62c15b05630ddccd5a1db1 (stylo-rebase), bindings regen in https://github.com/servo/servo/pull/12631

**Comment by Manishearth** [comment]
synced

**Comment by bholley** [comment]
CC @shinglyu @heycam @upsuper @SimonSapin

**Comment by bholley** [comment]
Waiting on https://github.com/servo/servo/pull/12725 to land, once it does we can switch to:

https://github.com/servo/gecko-dev/tree/stylo-rebase

**Comment by heycam** [comment]
Pushed the rebase: 40a650263cc69df52ea026d51e38dd80836ee9b0

**Comment by bholley** [comment]
Updated along with https://github.com/servo/servo/pull/12803

**Comment by Manishearth** [comment]
Hm, now fails at `Assertion failure: mURIResolved && aOther.mURIResolved (How do you know the URIs aren't null?), at /Users/manishearth/mozilla/quantum-central/layout/style/nsCSSValue.cpp:2644
#01: mozilla::css::URLValueData::URIEquals(mozilla::css::URLValueData const&) const[/Users/manishearth/mozilla/quantum-central/obj-x86_64-apple-darwin15.3.0/dist/NightlyDebug.app/Contents/MacOS/XUL +0x4e05749]`. I'm on 9e1c5bf4a5a266d96f70b78e3a6f6f712dd72204

**Comment by Manishearth** [comment]
That crash gets fixed by https://reviewboard.mozilla.org/r/69836/diff/1#0 , which we can cherry-pick.

But the other crash still happens:

```
thread '<unnamed>' panicked at 'assertion failed: !raw_initial_values().is_null()', /Users/manishearth/mozilla/sneutrino/target/geckolib/debug/build/style-5f5af2e3ceae093f/out/gecko_properties.rs:286
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I'm on gecko-dev 9e1c5bf4a5a266d96f70b78e3a6f6f712dd72204 (stylo branch) and servo 1b2450339c40dbcb65e94a346ea434d45f0edf90

**Comment by bholley** [comment]
@Manishearth That sounds like https://bugzilla.mozilla.org/show_bug.cgi?id=1292279

Can you check whether the main thread stack is either in nsXBLBinding::InstallAnonymousContent or nsCSSFrameConstructor::GetAnonymousContent ?

I'm working on a fix, hopefully will have one tomorrow. In the mean time, you might be able to just comment out that eager restyle during anonymous content creation. That will cause Servo_GetComputedValues to hit the bailout case and return the default computedValues, but that might be ok as a stopgap.

**Comment by Manishearth** [comment]
So I switched to single-process mode to debug it. And the crash disappeared. Wunderbar.

**Comment by Manishearth** [comment]
Oh, of course that's broken in multiprocess mode, we probably don't initialize per-process.

**Comment by bholley** [comment]
Are you talking about with/without --disable-e10s? Currently disabling e10s is the only "supported" configuration for stylo.

**Comment by Manishearth** [comment]
Huh, I thought I had done that, but it turns out that's not the case. We should list it in the stylo doc (I assume it's a mozconfig option?)

**Comment by bholley** [comment]
No, it's a ./mach arg, and it's already in the etherpad.

**Comment by Manishearth** [comment]
Ah, I see. I switched to building from the terminal (previously was building from sublime, which had this set), and totally forgot about that. Thanks!

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/12826 will land along with https://github.com/servo/gecko-dev/commit/ba191ba25dde58a07c0dab30681d1541b6f1557f (currently on stylo-rebase)

**Comment by Manishearth** [comment]
Synced to ba191ba25dde58a07c0dab30681d1541b6f1557f with https://github.com/servo/servo/commit/fc7053e030999ed118c9cf2cac0835286d6dde06

**Comment by Manishearth** [comment]
Rebase in stylo-rebase branch, to be forwarded when https://github.com/servo/servo/pull/12878 lands

**Comment by Manishearth** [comment]
Rebased to 340b94a4caef992c1c0b89225387f99ea6389b24 with servo at https://github.com/servo/servo/commit/3895b7118eba982891a6d592b11cd08fb7083dbb

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/12895 depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1292618 which is in inbound but hasn't landed yet. I rebased over inbound and pushed to stylo-rebase. Will re-rebase when it hits m-c.

**Comment by Manishearth** [comment]
https://github.com/servo/servo/pull/12945 will land, but https://bugzilla.mozilla.org/show_bug.cgi?id=1297064 hasn't been reviewed/landed yet. Corresponding patch to cherry-pick can be found at https://github.com/Manishearth/gecko-dev/tree/bgarray-minamata (https://github.com/Manishearth/gecko-dev/commit/001a1db66206bab495e52469d5c4ec5633be3a86 at this moment). I'll also forward stylo-rebase to stylo once m-i merges

**Comment by Manishearth** [comment]
Rebased stylo to include https://bugzilla.mozilla.org/show_bug.cgi?id=1296186 (cherry-picked for now)

stylo-rebase also contains https://bugzilla.mozilla.org/show_bug.cgi?id=1297064 for when servo/servo#12945 lands

**Comment by Manishearth** [comment]
Updated to ee3d2ba1cce9a4ea72ad79f28410868a4f63a98f to work with https://github.com/servo/servo/commit/c5e81f836190ea64df95f67c922b8421a4d2ff78

**Comment by Manishearth** [comment]
Rebased to 58b568de8a7b16316aa6a0125f4be9f81fda2288 to include the name changes. Now up to servo/servo@5b46a591946e4fc72461481ab361970f49d5af6b

**Comment by bholley** [comment]
Updated to https://github.com/servo/gecko-dev/commit/928685441158ee88cbc94090055e0d769c5d15b1 and https://github.com/servo/servo/commit/b98c17fab5c426bfea97c27e7d65bd3f6333a387

**Comment by bholley** [comment]
Updated again to https://github.com/servo/gecko-dev/commit/7f0262e9054aac9f44ee307ea2d1b9a2f2993da3 to pick up the latest m-c merge. With that, we have no more in-tree patches in either m-c or s/s! This should make things much easier for @larsbergstrom.

It depends on the binding regen in #13067, which is currently running through CI (I eagerly pushed because I don't think anybody will be pulling in the next half hour and I need to head out). If you do happen to pull before #13067 merges, you'll want to cherry-pick it.

**Comment by bholley** [comment]
This branch is now obsolete - please use https://hg.mozilla.org/incubator/stylo

**Comment by Manishearth** [comment]
I thought that that repo doesn't 2-way sync yet? (even if via a non-automated script?)

What's the workflow supposed to be now for PRs touching both Servo and Gecko? And how do we sync?

**Comment by bholley** [comment]
Workflow is pretty similar - land things separately, and then we update the incubator to pull in new things from m-c and s/s master.

The main difference is that we're using a pinned revision of Servo rather than always trying to be compatible with servo tip. Things should land on m-c first and then s/s, since it's easier to cherry-pick servo commits than m-c commits (we track m-c with merges, while we track s/s with rm -rf && cp -r).

**Comment by Manishearth** [comment]
I'm not sure how that will work.

Let's say I wish to make a change spanning s/s and m-c. I'll have to make a patch and PR, just as we do now.

But the servo PR needs to be made from a Servo clone. The current one in-tree is not a git repo, and doesn't contain all the files that servo does (so `git init` will not work), so we need to move patches back and forth. This will get extremely cumbersome if there are multiple commits on the servo side (and I want to preserve commit history).

This seems like a major disadvantage over the older workflow (until the sync tooling exists). The advantage is that we can run try builds, but try builds don't need to preserve commit history so can be run by copying merged patches over to an incubator clone.

A better workflow for now might be to have a faux-submodule in the incubator repo. This is a file with a hash, and mach pulls in the corresponding s/s commit when asked. Try can be made to work with this (since try can access github), and we locally have both repos to make PRs from.

Though in this world patches would have to land in s/s first so that the commit can be pinned to correctly. That's not ideal either, and multiple different people making changes at once is icky.

**Comment by bholley** [comment]
> This will get extremely cumbersome if there are multiple commits on the servo
> side (and I want to preserve commit history).

I'm not convinced. You can export the patches by doing |git format-patch BASE_COMMIT servo/|, which will generate a set of subcommits that represent the changes to that directory since BASE_COMMIT. You can then |git am| them into a servo repo to push to github.

> The advantage is that we can run try builds

That is one advantage. The other advantage is that we can _develop_ changes that span both repos using atomic commits. This is, IMO, the biggest productivity win that I'm looking forward to.

> but try builds don't need to preserve commit history

To be clear, you can copy patches in both directions while preserving commit history using git format-patch and git am.

If you prefer the ability to work from a bonafide servo repo over the ability to write cross-repo commits, you can easily just delete the servo/ directory in your local tree, copy in a real repo, and then checkout the same commit as was vendored.

**Comment by Manishearth** [comment]
Oh, didn't know format-patch could be given that argument. Thanks!

**Comment by Manishearth** [comment]
> If you prefer the ability to work from a bonafide servo repo over the ability to write cross-repo commits, you can easily just delete the servo/ directory in your local tree

Have to undo/redo this every time I want to push to try then.

And you have to do the same patch juggling on the gecko side, too. In the new system I'm maintaining an m-c clone, an incubator clone, and a s/s clone; making patches in the incubator and grafting them over to the m-c and s/s clones. This is worse than just having two clones which make independent patch sets, because we still have that, there's just a third repo in the middle. The reverse workflow is easier; grafting patches to the third repo and pushing to try (which is a rarer occurrence than updating/rebasing patches -- I push to try once or twice per PR, but I add/edit commits for review many, many times).

Also, what's the plan for updating stylo-integration?

I'm not really sure what the advantage of cross-repo atomic commits are. Until m-c is vendoring servo, they'll get split up anyway. Making two commits in different repos instead of one doesn't seem like a major issue; I personally haven't felt any loss of productivity due to that (though others may have, idk).

**Comment by Manishearth** [comment]
If mozreview could be set up to handle incubator patches, this would be much nicer. Workflow becomes: Make a bug, develop in incubator clone, push to mozreview, wait for r+, _do not merge_, graft patches to servo and m-c clones, make PRs/patches which are directly r+d.

I'm fine with grafting commits once during the review process, but less so about grafting it for each review cycle. At least in my case, I end up pushing very often.

**Comment by bholley** [comment]
You can always use separate repos if you like - there's really nothing being taken away here. The only thing that's changing is the mechanism for identifying the canonical pair of commits.

I don't see any technical reason why we shouldn't be able to push incubator changesets to MozReview - we just need to make sure it understands the correct base revision. @indygreg, would this be an easy thing to do?

**Comment by Manishearth** [comment]
> You can always use separate repos if you like - there's really nothing being taken away here

Yes, which is why I want to continue keeping this fork around 😄 (even if it's just following the hashes of the incubator repo)

Though this may end up to not be necessary. Hopefully.

**Comment by Manishearth** [comment]
One thing we'd need to be wary about with mozreview is autoreview -- it could end up confusing the two repos.

**Comment by Manishearth** [comment]
Aside from having reviews in one place, the other advantage of using incubator+mozreview is that it's closer to the final workflow once the autolanders work, so we'll be able to catch any issues early.

**Comment by bholley** [comment]
> Yes, which is why I want to continue keeping this fork around

If the canonical hashes are determined by the incubator repo, and we're not cherry-picking any gecko commits, it's not clear to me what value this branch adds, since you can just point your local checkout of m-c to the same rev as incubator. You are of course free to update this branch as you like if you find that helpful.
